### ISSUE TITLE
Fix app initialization

### ISSUE THREAD

**Issue by 95Rawan** [osamagamal7/express_crash_course#3]
Hi there, great work you've done here, I just wanted to point out that you made a simple mistake in this section of the material:
we're gonna start off by creating a simple Express Server.
```
//bring in express
const express = require('express')

// initialize a variable called app with express
const app = require();

// we need to listen on a port
const PORT = process.env.PORT || 5000;
app.listen(PORT, ()=> console.log(`server is running on ${PORT}`))
```

You wrote: ```const app = require();```
Instead of: ```const app = express();```

**Comment by osamagamal7** [comment]
yep, just found out that typo in README file. thanks for pointing this out.

**Comment by 95Rawan** [comment]
You're very welcome.
